version: "2"

services:
    db:
        image: mysql:5.7
        volumes:
            - "./data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        command: mysqld --default-time-zone="Asia/Tokyo" --explicit_defaults_for_timestamp=1 --log_error_verbosity=1

    redis:
        image: redis:3.2.9
        volumes:
            - "./data/redis:/data"
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes --requirepass foobared

    web:
        build: .
        ports:
            - "80:80"
        privileged: true
        volumes:
            - "./myapp/:/var/www/html"
            - "./config/httpd.conf:/etc/httpd/conf/httpd.conf"
            - "./config/php.ini:/etc/php.ini"
        links:
            - db
            - redis